apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: busybox
      script: |
        #!/bin/sh
        echo "Performing cleanup..."
        # Example of cleanup commands
        rm -rf /workspace/output/*
        echo "Cleanup completed"
